"""ADR-19 (CLAUDE.md §14.3) — emit a blank `<video>.annotations.txt` template, pre-filled from a
prior ADR-15 run's own `identity_report.json`, naming exactly which takes came back unverified so
the owner/client knows where a manual line is actually needed.

Never invents an annotation line itself (Golden Rule 5: a jersey number/colour/action can only
ever come from a human who watched the footage) — every unverified take becomes a comment block
with its own time range, followed by one blank example line the client edits in place.

Usage::

    .venv/bin/python scripts/make_annotation_template.py "input/Jordan Thomas Highlight Video.mp4"
    .venv/bin/python scripts/make_annotation_template.py <video> --identity-report <path> --force
"""

from __future__ import annotations

import sys
from pathlib import Path

import typer

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from src.common.io import load_json, work_dir_for  # noqa: E402
from src.common.logging import get_logger  # noqa: E402

logger = get_logger("make_annotation_template")
app = typer.Typer(add_completion=False)


def _format_mmss(seconds: float) -> str:
    minutes = int(seconds // 60)
    secs = seconds - minutes * 60
    return f"{minutes:02d}:{secs:04.1f}"


def build_template_text(identity_report: dict) -> str:
    """Pure text-building step (unit-testable without any file I/O): one comment block per
    UNVERIFIED take (`TakeIdentityResult.status != "verified"`, `src/identity/verify.py`), each
    followed by one blank example line in the CLAUDE.md §14.3 grammar for the client to edit in
    place. A report with every take already verified gets a short, honest header and no take
    blocks at all — never a padded/fabricated example (Golden Rule 5).
    """
    takes = identity_report.get("takes", [])
    unverified = [t for t in takes if t.get("status") != "verified"]

    lines = [
        "# Auto-generated by scripts/make_annotation_template.py from this video's own",
        f"# identity_report.json ({identity_report.get('video', '?')}).",
        "#",
        "# Grammar (CLAUDE.md §14.3): [Min ]MM:SS player #<number> in <colour> <action phrase>",
        "# Replace each example line below with what you actually saw at that timestamp -- one",
        "# line per event. Delete a take's block entirely if you don't want to annotate it.",
    ]

    if not unverified:
        lines.append("#")
        lines.append(
            "# Every take in this video's identity_report.json was already VERIFIED -- there is "
            "nothing"
        )
        lines.append(
            "# this template needs to fill in. Add lines below only if you want to correct or "
            "extend"
        )
        lines.append("# the auto-detected events.")
        return "\n".join(lines) + "\n"

    for take in unverified:
        take_id = take.get("take_id")
        confidence = take.get("confidence", 0.0)
        lines.append("#")
        lines.append(
            f"# Take {take_id}: status={take.get('status')} confidence={confidence:.2f} -- "
            "watch this segment and add your own line(s) below."
        )
        lines.append("Min MM:SS player #<N> in <colour> <action>")

    return "\n".join(lines) + "\n"


@app.command()
def main(
    video: Path = typer.Argument(..., help="Path to the video (as passed to `make run`)."),
    identity_report: Path | None = typer.Option(
        None,
        "--identity-report",
        help=(
            "Path to identity_report.json. Defaults to output/<slug>/identity_report.json, "
            "where <slug> matches src.common.io.work_dir_for()'s own slug for VIDEO."
        ),
    ),
    output_root: Path = typer.Option(Path("output")),
    force: bool = typer.Option(
        False, "--force", help="Overwrite an existing <video>.annotations.txt sidecar if present."
    ),
) -> None:
    """Write `input/<video_stem>.annotations.txt` (or wherever VIDEO lives) from a prior ADR-15
    run's own `identity_report.json` for that video."""
    if identity_report is None:
        slug = work_dir_for(video, root="work").name
        identity_report = output_root / slug / "identity_report.json"

    if not identity_report.exists():
        logger.error(
            "%s does not exist -- run the pipeline on %s first (it writes "
            "output/<slug>/identity_report.json for any filename-less video, ADR-15) or pass "
            "--identity-report explicitly.",
            identity_report,
            video,
        )
        raise typer.Exit(code=1)

    report = load_json(identity_report)
    template_text = build_template_text(report)

    out_path = video.parent / f"{video.stem}.annotations.txt"
    if out_path.exists() and not force:
        logger.error(
            "%s already exists -- pass --force to overwrite it (never overwritten silently, "
            "CLAUDE.md §10).",
            out_path,
        )
        raise typer.Exit(code=1)

    out_path.write_text(template_text)
    n_unverified = sum(1 for t in report.get("takes", []) if t.get("status") != "verified")
    logger.info(
        "wrote %s (%d unverified take(s) of %d total) -- edit it, then re-run `make run` to "
        "enter manual-events mode for this video",
        out_path,
        n_unverified,
        len(report.get("takes", [])),
    )


if __name__ == "__main__":
    app()
